import Head from "next/head";
import RockPaperScissors from "./rock-paper-scissors";
// import styles from '../styles/Home.module.css'
import Layout from "../Layout";

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <p>jfdisodssjkdnkj</p>
      </Layout>
    </div>
  );
}

export default Home;
